language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install: "pip install ."
# command to run tests
script:
  - "py.test -v tests/authorization_test.py"
  - "py.test -v tests/online_test.py"
